---

#- name: install python bindings for selinux
#  yum: name={{item}} state=present
#  with_items: 
#  - libselinux-python
#  - libsemanage-python

- name: test to see if SeLinux is running
  command: getenforce
  register: sestatus
  changed_when: false
